# fly.toml app configuration file generated for inmohelp on 2023-09-02T17:46:42-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "inmohelp"
primary_region = "mia"
console_command = "php /var/www/html/artisan tinker"

[build]
[build.args]
NODE_VERSION = "18"
PHP_VERSION = "8.2"

[env]
APP_ENV = "production"
FRONTEND_URL = "http://localhost:3000"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"
LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
DB_CONNECTION = "pgsql"
BROADCAST_DRIVER = "log"
CACHE_DRIVER = "file"
FILESYSTEM_DISK = "local"
QUEUE_CONNECTION = "sync"
SESSION_DRIVER = "cookie"
SESSION_SECURE_COOKIE = "true"
SESSION_LIFETIME = 120
MEMCACHED_HOST = "127.0.0.1"
REDIS_HOST = "127.0.0.1"
REDIS_PASSWORD = "null"
REDIS_PORT = 6379
MAIL_MAILER = "smtp"
MAIL_HOST = "mailpit"
MAIL_PORT = 1025
MAIL_USERNAME = "null"
MAIL_PASSWORD = "null"
MAIL_ENCRYPTION = "null"
MAIL_FROM_ADDRESS = "hello@example.com"
MAIL_FROM_NAME = "${APP_NAME}"
AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_DEFAULT_REGION = "us-east-1"
AWS_BUCKET = ""
AWS_USE_PATH_STYLE_ENDPOINT = false
PUSHER_APP_ID = "null"
PUSHER_APP_KEY = "null"
PUSHER_APP_SECRET = "null"
PUSHER_HOST = "null"
PUSHER_PORT = 443
PUSHER_SCHEME = "https"
PUSHER_APP_CLUSTER = "mt1"
VITE_PUSHER_APP_KEY = "${PUSHER_APP_KEY}"
VITE_PUSHER_HOST = "${PUSHER_HOST}"
VITE_PUSHER_PORT = "${PUSHER_PORT}"
VITE_PUSHER_SCHEME = "${PUSHER_SCHEME}"
VITE_PUSHER_APP_CLUSTER = "${PUSHER_APP_CLUSTER}"
SESSION_DOMAIN = "localhost"
SANCTUM_STATEFUL_DOMAINS = "localhost:3000"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
